general {
    # Акцентний колір (наприклад, для виділення вибраних пунктів)
    # Формат: ARGB (Alpha-Red-Green-Blue)
    accent = 0xff7aa2f7

    # Шрифт для інтерфейсу
    # font_family = JetBrains Mono Nerd Font
    font_size = 18

    # Радіус закруглення кутів
    rounding = 10
}

colors {
    # Основний фон вікон (темно-сірий)
    bg = 0xff1a1b26
    
    # Колір тексту
    fg = 0xffc0caf5
    
    # Колір виділення (Background highlight)
    selection = 0xff33467c
}
